### ISSUE TITLE
关于训练的精度

### ISSUE THREAD

**Issue by guofuzheng** [IDKiro/action-recognition#1]
您好，我昨天下载了您的代码。我在我自己想用的数据库和您的Google Drive的数据上跑训练的时候，Top1一直是0，就像这个图片这个样子。而且测试的精度也一直不变化，2%。所以麻烦您帮我解答一下这个问题，谢谢。
![screenshot from 2019-02-27 21-15-51](https://user-images.githubusercontent.com/25239334/53493007-3dc0c780-3ad5-11e9-84c0-0e0bcc9b4ee2.png)

**Comment by IDKiro** [comment]
不好意思，我一直没看到这个issue，我今天刚迁移了代码到新的pytorch版本，顺便修改了代码，你现在跑的话应该会比较顺利地收敛。
