### ISSUE TITLE
the dataset is not download

### ISSUE THREAD

**Issue by silence222** [IDKiro/action-recognition#2]
the provided google device is not a avaliable address. Does anyone download this dataset? please help me, thank you.

**Comment by IDKiro** [comment]
i am sorry that the dataset may miss since this code was write long time ago.
if you urgently need this code, i'll reorganize it when i am not busy.

**Comment by silence222** [comment]
thank you.  I really need this code, thank fou you work.

**Comment by IDKiro** [comment]
I have made a big update, you can try it now.

**Comment by silence222** [comment]
thank you for your update,i  do it  now
| |
lek_silence
|
|
lek_silence@163.com
|
签名由网易邮箱大师定制
On 11/21/2019 13:39，IDKiro<notifications@github.com> wrote：

Closed #2.
